server:
  port: ${SERVER_PORT:8888}
  servlet:
    context-path: ${CONTEXT_PATH:/}
  use-forward-headers: true
  tomcat:
    remote-ip-header: x-forwarded-for
    protocol-header: x-forwarded-proto
    port-header: x-forwarded-port
    accesslog:
      enabled: false

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/bremersee/config
          default-label: master

logging:
  level:
    org.springframework: ${LOG_LEVEL_SPRING:INFO}
    org.bremersee: ${LOG_LEVEL_BREMERSEE:DEBUG}

---

spring:
  profiles: docker
  cloud:
    config:
      server:
        git:
#         this will be a local copy of the repo:
          basedir: ${GIT_BASEDIR:/var/lib/config-server/basedir}
          uri: ${GIT_URI:https://github.com/bremersee/config}
          default-label: ${GIT_DEFAULT_LABEL:master}
          ignore-local-ssh-settings: ${GIT_IGNORE_LOCAL_SSH_SETTINGS:false}
          private-key: ${GIT_PRIVATE_KEY:}
          host-key: ${GIT_HOST_KEY:AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==}
          host-key-algorithm: ${GIT_HOST_ALGORITHM:ssh-rsa}
#          known-hosts-file: ${GIT_KNOWN_HOSTS_FILE:/etc/config-server/known_hosts}
  security:
    user:
      name: ${SECURITY_USER:user}
      password: ${SECURITY_PASSWORD:changeit}

server:
  tomcat:
    accesslog:
      enabled: ${SERVER_ACCESSLOG_ENABLED:false}
      directory: ${SERVER_ACCESSLOG_DIRECTORY:/var/log}
