spring:
  application:
    name: config-server

  profiles:
    active: default,composite

  # Example of a composite configuration
  cloud:
    config:
      server:
        fail-on-composite-error: false
        default-label: develop
        composite:
          - type: git
            uri: https://github.com/${ORGANISATION:bremersee}/{application}
            basedir: ${DATA_DIR:${java.io.tmpdir}}/git
          - type: git
            uri: https://github.com/${ORGANISATION:bremersee}/config
            basedir: ${DATA_DIR:${java.io.tmpdir}}/git/config

encrypt:
  key-store:
    location: ${ENCRYPTION_KEYSTORE_LOCATION:classpath:/encryption.jks}
    type: ${ENCRYPTION_KEYSTORE_TYPE:jks}
    password: ${ENCRYPTION_KEYSTORE_PASSWORD:changeit}
    alias: ${ENCRYPTION_KEYSTORE_ALIAS:encryption}
    secret: ${ENCRYPTION_KEYSTORE_SECRET:changeit}

logging:
  level:
    org.springframework: INFO
    org.bremersee: INFO
  file:
    name: ${DATA_DIR:${java.io.tmpdir}}/log/config-server.log
  logback:
    rollingpolicy:
      max-history: 25

management:
  endpoints:
    web:
      exposure:
        include: "*"
      cors:
        allowed-headers: "*"
        allowed-methods: "*"
        allowed-origins: "*"
  endpoint:
    health:
      show-details: when_authorized
    logfile:
      external-file: ${logging.file.name}

bremersee:
  access:
    application-access: "false"
    actuator-access: "false"
    client-user-name: ${CLIENT_USER:user}
    client-user-password: ${CLIENT_PASSWORD:changeit}
    actuator-user-name: ${ACTUATOR_USER:actuator}
    actuator-user-password: ${ACTUATOR_PASSWORD:changeit}
    admin-user-name: ${ADMIN_USER:admin}
    admin-user-password: ${ADMIN_PASSWORD:changeit}

---

spring:
  config:
    activate:
      on-profile: test
  cloud:
    config:
      server:
        git:
          uri: https://github.com/bremersee/config-server
          default-label: develop
          basedir: ./git-base-dir

encrypt:
  key-store:
    location: classpath:/encryption.jks
    password: changeit
    alias: encryption
    secret: changeit

logging:
  level:
    org.springframework: INFO
    org.bremersee: DEBUG

