server:
  port: ${SERVER_PORT:8888}
  servlet:
    context-path: ${CONTEXT_PATH:/}
  use-forward-headers: true
  tomcat:
    remote-ip-header: x-forwarded-for
    protocol-header: x-forwarded-proto
    port-header: x-forwarded-port
    accesslog:
      enabled: false

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/bremersee/config
          default-label: master

---

spring:
  profiles: docker
  cloud:
    config:
      server:
        git:
#         this will be a local copy of the repo:
          basedir: ${GIT_BASEDIR:/opt/data/basedir}
          uri: ${GIT_URI:https://github.com/bremersee/config}
          default-label: ${GIT_DEFAULT_LABEL:master}
          ignore-local-ssh-settings: ${GIT_IGNORE_LOCAL_SSH_SETTINGS:false}
          private-key: ${GIT_PRIVATE_KEY:}
          known-hosts-file: ${GIT_KNOWN_HOSTS_FILE:/opt/known_hosts}
  security:
    user:
      name: ${SECURITY_USER:user}
      password: ${SECURITY_PASSWORD:changeit}

server:
  tomcat:
    accesslog:
      enabled: ${SERVER_ACCESSLOG_ENABLED:false}
      directory: ${SERVER_ACCESSLOG_ENABLED:/opt/data/logs}
