#!/bin/sh
if [ -z "$ENCRYPTION_KEY_STORE_PASSWORD" ] && [ ! -z "$ENCRYPTION_KEY_STORE_PASSWORD_FILE" ] && [ -e $ENCRYPTION_KEY_STORE_PASSWORD_FILE ]; then
  export ENCRYPTION_KEY_STORE_PASSWORD="$(cat $ENCRYPTION_KEY_STORE_PASSWORD_FILE)"
fi
if [ -z "$ENCRYPTION_KEY_STORE_SECRET" ] && [ ! -z "$ENCRYPTION_KEY_STORE_SECRET_FILE" ] && [ -e $ENCRYPTION_KEY_STORE_SECRET_FILE ]; then
  export ENCRYPTION_KEY_STORE_SECRET="$(cat $ENCRYPTION_KEY_STORE_SECRET_FILE)"
fi
if [ -z "$CLIENT_USER_PASSWORD" ] && [ ! -z "$CLIENT_USER_PASSWORD_FILE" ] && [ -e $CLIENT_USER_PASSWORD_FILE ]; then
  export CLIENT_USER_PASSWORD="$(cat $CLIENT_USER_PASSWORD_FILE)"
fi
if [ -z "$ACTUATOR_USER_PASSWORD" ] && [ ! -z "$ACTUATOR_USER_PASSWORD_FILE" ] && [ -e $ACTUATOR_USER_PASSWORD_FILE ]; then
  export ACTUATOR_USER_PASSWORD="$(cat $ACTUATOR_USER_PASSWORD_FILE)"
fi
if [ -z "$ADMIN_USER_PASSWORD" ] && [ ! -z "$ADMIN_USER_PASSWORD_FILE" ] && [ -e $ADMIN_USER_PASSWORD_FILE ]; then
  export ADMIN_USER_PASSWORD="$(cat $ADMIN_USER_PASSWORD_FILE)"
fi
if [ -z "$GIT_PRIVATE_KEY" ] && [ ! -z "$GIT_PRIVATE_KEY_FILE" ] && [ -e $GIT_PRIVATE_KEY_FILE ]; then
  export GIT_PRIVATE_KEY="$(cat $GIT_PRIVATE_KEY_FILE)"
fi
java -Djava.security.egd=file:/dev/./urandom -Dspring.profiles.active=docker -jar /opt/app.jar
